baseurl = "https://example.com"
title = "Insightful data"
author = "Clinton Oyogo"
copyright = "Copyright © 2020,clinton oyogo."
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = "Clinton Oyogo"
introDescription = "Data driven decision making is much needed now than ever..."
contentSharing = "I'm happy for you to share content on this site, but please provide attribution."

[social]
linkedin = "oyogo-clinton-53359198"
twitter = "OyogoDavid"

