baseurl = "https://oyogoclinton.netlify.app"
title = "Insightful analytics"
author = "Clinton Oyogo"
copyright = "Copyright © 2021,clinton oyogo."
canonifyurls = true
paginate = 3
theme = "silhouette-hugo"

pygmentsUseClasses=true

#disqusShortname = ""
#googleAnalytics = ""

[params]
author = "Clinton Oyogo"
introDescription = "Turning data into actionable insights."
contentSharing = "I'm happy for you to share content on this site, but please provide attribution."

[social]
linkedin = "oyogo-clinton-53359198"
twitter = "OyogoDavid"

